openSUSE/agile-team-dashboard

app/helpers/application_helper.rb

Fix error on team member page

---

Gemfile
Gemfile.lock
app/helpers/application_helper.rb
app/views/shared/_sidebar.html.slim

We add this gem to generate an identify.

Add identicon gem

---

app/assets/javascripts/custom.coffee
app/controllers/dashboards_controller.rb
app/controllers/sprints_controller.rb
app/models/meeting.rb
app/models/sprint.rb
app/services/create_meetings.rb
app/views/absences/_form.html.slim
app/views/dashboards/index.html.slim
app/views/sprints/_form.html.slim
app/views/sprints/index.html.slim
db/migrate/20170829101131_add_name_to_sprint.rb
db/schema.rb
spec/factories/sprints.rb
spec/models/meeting_spec.rb
spec/services/create_meetings_spec.rb

When we create a new sprint, we also generate the corresponding meetings for this sprint

Sprint automatically create meetings

---

.rubocop.yml
app/services/create_meetings.rb

`Rails/SaveBang` offenses were automatically corrected. :bowtie:

Enable Rails Rubocop cop

---

Gemfile
Gemfile.lock
spec/controllers/meetings_controller_spec.rb
spec/factories/users.rb
spec/models/meeting_spec.rb
spec/models/user_spec.rb

Randomize user factory using Faker and remove David's originality. Also test `User#fullname`. :bowtie:

User tests

---

app/controllers/dashboards_controller.rb
app/models/pull_request.rb

to move the github access methods to the PullRequest class

Refactor Dashboard controller

---

app/controllers/dashboards_controller.rb
app/models/user.rb
app/views/dashboards/index.html.slim
spec/models/user_spec.rb

Add birthdays

---

.slim-lint.yml
Gemfile
Gemfile.lock
Rakefile
app/views/layouts/mailer.html.slim
app/views/meetings/index.html.slim
app/views/users/confirmations/new.html.slim
app/views/users/mailer/confirmation_instructions.html.slim
app/views/users/mailer/password_change.html.slim
app/views/users/mailer/reset_password_instructions.html.slim
app/views/users/mailer/unlock_instructions.html.slim
app/views/users/registrations/edit.html.slim
app/views/users/registrations/new.html.slim
travis_script.sh

Add slim-lint gem

---

app/controllers/absences_controller.rb
app/controllers/meetings_controller.rb
app/controllers/sprints_controller.rb
app/controllers/team/members_controller.rb
app/views/layouts/application.html.slim

We change the flash message to be more specific.

Add flash messages

---

provisioning/bootstrap.sh

If you delete your database and want to create it again this comprobation will make the app fail, and I don't see any benefit on having this.

Configure the database always

---

Gemfile
Gemfile.lock
app/models/meeting.rb
config/clock.rb

Add a `config/clock.rb` file to update the Burndown Chart and upload it to Trello between 5 and 20 minutes before the Standup and between 30 and 45 minutes after the Review.

Program the burndown char update

---

Gemfile
Gemfile.lock

Before this we fetched it from GitHub.
Fixes #58

Fetch semantic-ui-sass from rubygems.org

---

app/controllers/sprints_controller.rb
config/clock.rb
config/environment.rb

Upload the burndown char and data to Github on end of Sprint.
The following Github account is used for that:
https://github.com/bot-bs

Add Github upload at the end of the Sprint

---

app/controllers/sprints_controller.rb
app/models/sprint.rb
app/views/sprints/_form.html.slim
app/views/sprints/index.html.slim
db/migrate/20171005143737_add_number_to_sprint_and_remove_name.rb
db/schema.rb
spec/factories/sprints.rb
spec/models/sprint_spec.rb

We remove the attribute name and added number because trollolo needs a
number.
should resolve #75

Change name by number in Sprint

---

Gemfile
Gemfile.lock
app/controllers/sprints_controller.rb
app/models/sprint.rb
config/clock.rb

Point to Trollolo release and generate burndown char with correct number. :bowtie:

Trollolo release

---

app/controllers/meetings_controller.rb
app/models/meeting.rb
app/models/sprint.rb
app/services/create_meetings.rb
app/views/meetings/_form.html.slim
app/views/meetings/index.html.slim
db/migrate/20171009134130_add_sprint_id_to_event.rb
db/schema.rb
spec/controllers/meetings_controller_spec.rb
spec/factories/meetings.rb
spec/services/create_meetings_spec.rb

We need this association for generate the burndown-chart.

Add meeting association with sprint

---

app/controllers/team/members_controller.rb
app/views/team/members/edit.html.slim
db/schema.rb
spec/controllers/members_controller_spec.rb

seperate sections are created for password and remaining profile settings, on the same page
for the issue #73

Password isn't required to update profile (issue#73)

---

app/views/team/members/edit.html.slim

We moved the title of the form into its sections.

Move form title into `segment`

---

app/models/event.rb
app/models/meeting.rb
app/models/sprint.rb
spec/controllers/meetings_controller_spec.rb
spec/factories/meetings.rb
spec/models/absence_spec.rb
spec/models/event_spec.rb
spec/models/sprint_spec.rb

We added some missing validations and scopes.
Should resolve #60

Add some scopes and validations

---

app/models/meeting.rb
spec/models/meeting_spec.rb

Add missing event type in meeting

---

app/assets/stylesheets/base.scss
app/views/shared/_sidebar.html.slim

We change the padding between items.

Fix sidebar menu

---

.rubocop_todo.yml
Gemfile
Vagrantfile
app/controllers/absences_controller.rb
app/controllers/calendars_controller.rb
app/controllers/dashboards_controller.rb
app/controllers/meetings_controller.rb
app/controllers/sprints_controller.rb
app/controllers/team/members_controller.rb
app/models/absence.rb
app/models/event.rb
app/models/meeting.rb
git-cop_configuration.yml
lib/tasks/git-cop.rake
spec/models/absence_spec.rb
spec/models/event_spec.rb
spec/models/meeting_spec.rb
spec/models/sprint_spec.rb
spec/models/user_spec.rb

Solve the Rubocop offenses introduced in the last update which support autocorrection. :bowtie:

Solve the Rubocop offenses introduced in the last update

---

app/controllers/pages_controller.rb
app/views/shared/_sidebar.html.slim
config/routes.rb

Move the team info link inside a loop
Closes #55

Add links to the sidebar for Static Pages

---

app/views/team/members/edit.html.slim

Closes #111 
Added date picker for Birthday field input to make it convenient for the user to input date.

Added Date Picker for Birthday

---

app/assets/javascripts/custom.coffee
app/assets/stylesheets/base.scss
app/controllers/absences_controller.rb
app/controllers/meetings_controller.rb
app/views/absences/_form.html.slim
app/views/absences/_listing.html.slim
app/views/absences/edit.html.slim
app/views/absences/index.html.slim
app/views/absences/index.js.slim
app/views/meetings/_form.html.slim
app/views/meetings/_listing.html.slim
app/views/meetings/edit.html.slim
app/views/meetings/index.html.slim
app/views/meetings/index.js.slim
app/views/sprints/_listing.html.slim
config/locales/en.yml

**Meeting#index :**
**Absences#index :**
**changes in this PR :**
- Partials used for rendering code in meeting and absences index.
- pagination added to absences and meetings index using smart_listing.

Pagination added to Absence and Meeting

---

app/assets/javascripts/custom.coffee
app/assets/stylesheets/devise.scss
app/views/layouts/application.html.slim
app/views/layouts/devise.html.slim
app/views/shared/_flash-messages.html.slim

Add flash msgs to devise.html.slim and made flash msges closeable on clicking close icon

Add flash msgs to devise and made flash msges closeable

---

app/views/absences/new.html.slim
app/views/meetings/new.html.slim
config/locales/en.yml

Add class to absence and meeting's new form for better UI and update text for btns in forms.
meeting's  form :

Add grid class to Absence and meeting new forms

---

app/controllers/absences_controller.rb
app/controllers/meetings_controller.rb
app/controllers/sprints_controller.rb
app/models/sprint.rb
app/views/shared/_flash-messages.html.slim
spec/models/sprint_spec.rb

In the beginning, I added a horrible flash error messages :disappointed:  and we forget to add a uniqueness validation for the sprint number :see_no_evil:

Fix some mess up

---

app/controllers/sprints_controller.rb
app/models/sprint.rb
spec/controllers/sprints_controller_spec.rb
spec/models/sprint_spec.rb

We add a missing test for SprintController and also fix collision validation

SprintsController Tests
